"""add categories table

Revision ID: 6e8dfb211257
Revises: 693d0a6003af
Create Date: 2023-03-15 20:28:19.726190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8dfb211257'
down_revision = '693d0a6003af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
